server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: shop
    password: shop
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

logging:
  level:
    org.hibernate.SQL: debug
app:
  jwt:
    secret: "CHANGE_ME_TO_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS_123456"
    ttl-seconds: 86400